items:
  fishing_rod:
    resource:
      material: PAPER
      model_path: fishing_rod
      generate: false
    displayName: fishing_rod
  shield:
    resource:
      material: PAPER
      model_path: shield
      generate: false
    displayName: shield
  bow_0:
    resource:
      material: PAPER
      model_path: bow_0
      generate: false
    displayName: bow_0
  bow_2:
    resource:
      material: PAPER
      model_path: bow_2
      generate: false
    displayName: bow_2
  hammer:
    resource:
      material: PAPER
      model_path: hammer
      generate: false
    displayName: hammer
  bow_1:
    resource:
      material: PAPER
      model_path: bow_1
      generate: false
    displayName: bow_1
  pickaxe:
    resource:
      material: PAPER
      model_path: pickaxe
      generate: false
    displayName: pickaxe
  shovel:
    resource:
      material: PAPER
      model_path: shovel
      generate: false
    displayName: shovel
  bow:
    resource:
      material: PAPER
      model_path: bow
      generate: false
    displayName: bow
  scarecrow:
    resource:
      material: PAPER
      model_path: scarecrow
      generate: false
    displayName: scarecrow
  axe:
    attribute_modifiers:
      mainhand:
        attackSpeed: 1.1
    resource:
      material: PAPER
      model_path: axe
      generate: false
    displayName: axe
  sword:
    resource:
      material: PAPER
      model_path: sword
      generate: false
    displayName: sword
  chainsaw:
    resource:
      material: PAPER
      model_path: chainsaw
      generate: false
    displayName: chainsaw
  helmet:
    resource:
      material: PAPER
      model_path: helmet
      generate: false
    displayName: helmet
  pumkincap:
    resource:
      material: PAPER
      model_path: pumkincap
      generate: false
    displayName: pumkincap
  fishing_rod_cast:
    resource:
      material: PAPER
      model_path: fishing_rod_cast
      generate: false
    displayName: fishing_rod_cast
  shield_blocking:
    resource:
      material: PAPER
      model_path: shield_blocking
      generate: false
    displayName: shield_blocking
  hoe:
    resource:
      material: PAPER
      model_path: hoe
      generate: false
    displayName: hoe
info:
  namespace: pumpkin_saw_animated_weapon_set
